---
name: "TODOs"
permissions:
  issues: write
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  todos:
    uses: devantler-tech/reusable-workflows/.github/workflows/todos.yaml@15c6976081f64fe8cda55db05ae48e9662768e1e # v1.17.0
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
