---
name: "TODOs"
permissions:
  issues: write
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  todos:
    uses: devantler-tech/reusable-workflows/.github/workflows/todos.yaml@921200d092487fa7a49606612e5f988ae51c0408 # v1.16.2
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
